/*
 * This file was automatically generated by EvoSuite
 * Mon May 27 00:39:32 GMT 2024
 */

package Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Controller.ControladorEncomenda;
import Model.Vintage;
import View.Apresentacao;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class ControladorEncomenda_ESTest extends ControladorEncomenda_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      // Undeclared exception!
      try { 
        controladorEncomenda0.removerArtigo((Apresentacao) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretadorDevolver(apresentacao0, (Vintage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretadorAdiar(apresentacao0, (Vintage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretador(apresentacao0, (Vintage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      // Undeclared exception!
      try { 
        controladorEncomenda0.adicionarArtigo((Apresentacao) null, linkedList0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      Vintage vintage0 = new Vintage();
      controladorEncomenda0.interpretadorAdiar(apresentacao0, vintage0);
      assertNull(vintage0.getSessaoAtual());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      Vintage vintage0 = new Vintage();
      controladorEncomenda0.interpretadorDevolver(apresentacao0, vintage0);
      assertNull(vintage0.getSessaoAtual());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.removerArtigo(apresentacao0, (List<Integer>) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.adicionarArtigo(apresentacao0, linkedList0, linkedList0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = new Apresentacao();
      Vintage vintage0 = new Vintage();
      controladorEncomenda0.interpretador(apresentacao0, vintage0);
      assertNull(vintage0.getSessaoAtual());
  }
}
